---
title: "Inverse Forward Sampling Case Studies"
author: "Maximilian Scholz"
editor: visual
execute: 
  cache: true
  autodep: true
format:
  html:
    embed-resources: true
    smooth-scroll: true
    anchor-sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center", fig.retina = 3,
                      fig.width = 6, fig.height = (6 * 0.618),
                      out.width = "80%", collapse = TRUE,
                      dev = "png", dev.args = list(type = "cairo-png"))

options(digits = 3, width = 120,
        dplyr.summarise.inform = FALSE,
        knitr.kable.NA = "")
```

```{r load-libraries, warning=FALSE, message=FALSE}
library(tidyverse)
library(brms)
library(bayesim)
library(bayeshear)
library(patchwork)
library(tidybayes)
library(future)
library(SBC)
library(posterior)

set.seed(671328974)
plan(multisession)
options(brms.backend = "cmdstanr")
options(SBC.min_chunk_size = 5)
cache_dir <- "../_brms_SBC_cache"
```

```{r load-data}
data("epilepsy")
head(epilepsy)
```

```{r model-prep}
# Build the formula for a simple model
simple_formula <- bf(count ~ zAge + zBase * Trt) + negbinomial()
multilevel_formula <- bf(count ~ zAge + zBase * Trt + (1|patient)) + negbinomial()
spline_formula <- bf(count ~ s(zAge) + zBase * Trt + (1|patient)) + negbinomial()
default_prior = prior(student_t(3, 0, 2.5), class = "b")
wide_prior = prior(normal(0, 100), class = "b")
```

# Single-Level Example

## Simple Model SBC

```{r simple-model-fit, message=FALSE, warning=FALSE}
# Sample from the simple prior of the model with "default" priors
simple_fit_prior_only <- brm(simple_formula,
                             data = epilepsy,
                             sample_prior = "only",
                             prior = default_prior
                             )
# See, that it expects people to have 10^toomuch episodes...
pp_check(simple_fit_prior_only)
```

```{r simple-model-sbc, message=FALSE, warning=FALSE}
# SBC the model
template_data = data.frame(count = rep(0, 236),
                           zAge = rnorm(236),
                           zBase = rnorm(236),
                           Trt = as.numeric(rbernoulli(236)))
simple_plain_generator <- SBC_generator_brms(simple_formula,
                   data = template_data,
                   prior = default_prior,
                   thin = 50, warmup = 10000, refresh = 2000,
                   generate_lp = TRUE)

simple_plain_datasets <- generate_datasets(simple_plain_generator, 100)

simple_plain_backend <- SBC_backend_brms_from_generator(simple_plain_generator, chains = 1, thin = 1,
                            warmup = 500, iter = 1500,               
                            inits = 0.1)

simple_plain_results <- compute_SBC(simple_plain_datasets, simple_plain_backend,
                    cache_mode = "results", 
                    cache_location = file.path(cache_dir, "plain"))

plot_rank_hist(simple_plain_results)
plot_ecdf_diff(simple_plain_results)
```

## Preconditioning on 5% of data

```{r fit-preconditioned-model}
# Split the df into a preconditioning part and the rest
index <- sample(c(TRUE, FALSE), nrow(epilepsy), replace=TRUE, prob=c(0.95,0.05))
precondition_sample <- epilepsy[!index,]
reduced_epilepsy <- epilepsy[index,]

# Fit the model on the precondition sample
simple_fit_precondition <- brm(
  simple_formula, 
  data = precondition_sample,
  prior = default_prior,
  cores = 4
  )
pp_check(simple_fit_precondition)
```

## SBC from the forward sampling model

```{r FS-SBC-generator}
# We want to add the simulated dataset from the preconditioned model as a form
# of empirical prior to the usual prior simulated datasets
one_sim_generator <- function(n, fit, precon_sample, ...) {
  
  index <- sample.int(post_warmup_samples(fit), size = 1)
  dataset <- forward_sampling(fit, index, n, subset(precon_sample, select = -count), ...)
  pars <- as_draws_df(fit)[index,]
  attr(pars, "draws_df") = NULL
  pars <-   pars[ , -which(
    names(
      pars <- as_draws_df(fit)
      ) %in% c(".chain",".iteration", ".draw"))]
  
  list(
    variables = pars,
    generated = rbind(precon_sample[,colnames(dataset)], dataset)
  )
}
```

```{r FS-SBC-data, warning=FALSE, message=FALSE}
precon_simple_n_sims_generator <- SBC_generator_function(
  one_sim_generator,
  n = nrow(epilepsy), # ??? how many samples do we need?
  fit = simple_fit_precondition,
  precon_sample = precondition_sample)

precon_simple__datasets <- generate_datasets(precon_simple_n_sims_generator, 100)

precon_simple__backend <- SBC_backend_brms(simple_formula,  
                            prior = default_prior, chains = 1,
                            template_data = precon_simple__datasets$generated[[1]])


```

```{r FS-SBC-calc}
precon_results <- compute_SBC(precon_simple__datasets,
                              precon_simple__backend, 
                              cache_mode = "results", 
                              cache_location = file.path(cache_dir, "precon"))
plot_rank_hist(precon_results)
plot_ecdf_diff(precon_results)
```

# Multilevel Example

## Simple Model SBC

```{r ml-model-fit, message=FALSE, warning=FALSE}
# Sample from the simple prior of the model with "default" priors
ML_fit_prior_only <- brm(multilevel_formula,
                             data = epilepsy,
                             sample_prior = "only",
                             prior = default_prior
                             )
# See, that it expects people to have 10^toomuch episodes...
pp_check(ML_fit_prior_only)
```

```{r ml-model-sbc, message=FALSE, warning=FALSE}
# SBC the model
template_data = data.frame(count = rep(0, 236),
                           zAge = rnorm(236),
                           zBase = rnorm(236),
                           Trt = as.numeric(rbernoulli(236)),
                           patient = sample(unique(epilepsy$patient), size = 236, replace = TRUE))
ML_plain_generator <- SBC_generator_brms(multilevel_formula,
                   data = template_data,
                   prior = default_prior,
                   thin = 50, warmup = 10000, refresh = 2000,
                   generate_lp = TRUE)

ML_plain_datasets <- generate_datasets(ML_plain_generator, 100)

ML_plain_backend <- SBC_backend_brms_from_generator(ML_plain_generator, chains = 1, thin = 1,
                            warmup = 500, iter = 1500,               
                            inits = 0.1)

ML_plain_results <- compute_SBC(ML_plain_datasets, ML_plain_backend,
                    cache_mode = "results", 
                    cache_location = file.path(cache_dir, "ml"))

plot_rank_hist(ML_plain_results, variables = c(unique(ML_plain_results$stats$variable)[1:8], "lprior", "lp__"))
plot_ecdf_diff(ML_plain_results, variables = c(unique(ML_plain_results$stats$variable)[1:8], "lprior", "lp__"))
```

## Preconditioning on 5% of data

```{r ml-fit-preconditioned-model}
# Fit the model on the precondition sample
ml_fit_precondition <- brm(
  multilevel_formula, 
  data = precondition_sample,
  prior = default_prior,
  cores = 4
  )
pp_check(ml_fit_precondition)
```

## SBC from the forward sampling model

```{r ml-FS-SBC-data, warning=FALSE, message=FALSE}
ml_precon_n_sims_generator <- SBC_generator_function(
  one_sim_generator,
  n = nrow(epilepsy), # ??? how many samples do we need?
  fit = ml_fit_precondition,
  precon_sample = precondition_sample,
  allow_new_levels = TRUE)

ml_precon_simple__datasets <- generate_datasets(ml_precon_n_sims_generator, 100)

ml_precon_simple__backend <- SBC_backend_brms(multilevel_formula,  
                            prior = default_prior, chains = 1,
                            template_data = ml_precon_simple__datasets$generated[[1]])


```

```{r ml-FS-SBC-calc}
ml_precon_results <- compute_SBC(ml_precon_simple__datasets,
                              ml_precon_simple__backend, 
                              cache_mode = "results", 
                              cache_location = file.path(cache_dir, "ml_precon"))
plot_rank_hist(ml_precon_results, variables = c(unique(ml_precon_results$stats$variable)[1:8], "lprior", "lp__"))
plot_ecdf_diff(ml_precon_results, variables = c(unique(ml_precon_results$stats$variable)[1:8], "lprior", "lp__"))
```
